#!/usr/bin/env bash
set -x

TAG=${GITHUB_REF#refs/*/v}
ARCH=x86_64

if [[ "${OS}" == "macOS-latest" ]]; then
    VENDOR=apple
    OS=darwin
elif [[ "${OS}" == "windows-latest" ]]; then
    VENDOR=microsoft
    OS=windows
    EXT=.exe
else
    VENDOR=unknown
    OS=linux
fi

echo "PROGRAM_NAME=target/release/${PROGRAM_NAME}${EXT}" >> $GITHUB_ENV
echo "RELEASE_NAME=${PROGRAM_NAME}-${TAG}-${ARCH}-${VENDOR}-${OS}${EXT}" >> $GITHUB_ENV
